### ISSUE TITLE
Using a stacked image (OME.tiff)

### ISSUE THREAD

**Issue by arcolombo** [Hazmatius/MIBI_GUI#24]
Hello! 
 I so the sub-folders for TIFFs does upload correctly, but I am trying to use a stacked "OME" tiff file, however the software is returning an error "not enough labels".  This i think means that the labels are not indicated on the stacks of each OME tiff stack.   
how can I apply the labels to the OME file?  or what is the best way to unstack an OME file into individual TIFFs?

Thank you

**Comment by ngreenwald** [comment]
Hey @arcolombo, 
Sorry for the late response. We're not actively developing this project anymore. There isn't a way to read in OME TIFFs, it requires a folder of single-channel TIFFs. 

--Noah
