### ISSUE TITLE
Background removal error

### ISSUE THREAD

**Issue by veenstje** [Hazmatius/MIBI_GUI#25]
Hello, I'm trying out the first step with the background removal GUI using the demo data and am encountering the below errors. The demo data subfolders all appear to be formatted correctly based on the notes provided. Any thoughts to why this is happening? 

Saving to D:\MAUI-develop\MAUI-develop\demo_data\no_background\Point4\TIFs
Error using tifflib
Unable to open TIFF file "D:\MAUI-develop\MAUI-develop\demo_data\no_background\Point4\TIFs\C.tif".

Error in Tiff (line 660)
            obj.FileID = tifflib('open',filename,mode);

Error in saveTIFF_folder (line 4)
        tiff = Tiff([path, filesep, labels{index}, '.tif'], 'w');

Error in Point/save_no_background (line 201)
                saveTIFF_folder(countsNoBg, obj.labels, obj.tags, [new_path, filesep, obj.path_ext]);

Error in PointManager/save_no_background (line 687)
                    point.save_no_background();

Error in background_removal_gui>remove_background_Callback (line 549)
    pipeline_data.points.save_no_background();

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in background_removal_gui (line 47)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)background_removal_gui('remove_background_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Thank you

**Comment by ngreenwald** [comment]
Hey @veenstje, sorry for the delayed response, but we're no longer maintaining this code. We'll have a new package for background subtraction/denoising coming soon.
