### ISSUE TITLE
text display

### ISSUE THREAD

**Issue by ngreenwald** [Hazmatius/MIBI_GUI#3]
the text on the background removal GUI for Gaussian isn't rendered correctly

![image](https://user-images.githubusercontent.com/13770365/55378990-2871fb00-54d0-11e9-8f92-59cad925e469.png)

**Comment by christianrickert** [comment]
Same issue here: 
I'm using the "MIBI_GUI_notes.pdf" screenshots as a workaround.

![BackgroundRemovalWindow](https://user-images.githubusercontent.com/19319377/123487112-92ec4580-d5ca-11eb-8b3c-853e708891dc.PNG)

- MATLAB 9.9.0.1592791 (R2020b) Update 5
- Microsoft Windows [Version 10.0.19042.1052]

**Comment by ngreenwald** [comment]
Hey Chris, 
We've stopped actively developing MAUI, and are moving all of the functionality here into [AMP](https://github.com/angelolab/AMP). It's still in early beta, but if you'd like to give it a try @ackagel and I would love your feedback

**Comment by christianrickert** [comment]
Yes, I'll give AMP a try and provide feedback.
Have you considered archiving MAUI?

![RepoGeneralSettings](https://user-images.githubusercontent.com/19319377/123490241-eb264600-d5d0-11eb-8bf1-2c923cf377b3.PNG)

**Comment by ngreenwald** [comment]
Oh, that's a neat feature! Once the last remaining functionality has been ported over to AMP we'll definitely archive it.
